Mobile skeleton
AshwinCarvalho999/Portfolio-Mobile pull request #1
Opened 2022-07-23 06:40 UTC by AshwinCarvalho999

Added index.html
Added style.css
Added Linters
Created navbar section and aligned with flexbox
Created a Headline section for intro text and a brief message
Added attractive design and used various  font styles
Added gitignore file to ignore node_modules
Added and Edited Readme file

2022-08-15 15:15 UTC, cynthiainga requested changes
Hi @AshwinCarvalho999, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![](https://user-images.githubusercontent.com/20563252/121369265-4e418880-c901-11eb-848c-1eff06d5a4cf.gif)

## Highlights

- [ ] All linters are passing ✔️ 
- [ ] Descriptive Pull Request ✔️ 
- [ ] Good commit history ✔️ 

## Required Changes ♻️

- [ ] Please kindly check the comments under the review 👇 👇 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-15 15:15 UTC, cynthiainga commented on README.md
> +
- [ ] Please after this part makes sure to add the part that explains how to set up your app locally on the device, you can use this [this template](https://github.com/microverseinc/readme-template/blob/master/README.md) 🙃 🙃

2022-08-15 15:15 UTC, cynthiainga commented on README.md
> +Give a ⭐️ if you like it!
- [ ] Please kindly also add the `Acknowledgments`  part, you can also use this [template](https://github.com/microverseinc/readme-template/blob/master/README.md) 🙃 🙃

2022-08-17 09:09 UTC, BenMukebo approved these changes
<h1>Status: Approve  :champagne:  :+1: :confetti_ball: 

### **Hi @AshwinCarvalho999**, 

### **Congratulations! 🎉 Project Approved ✅**

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 


### To Highlight :1st_place_medal: 
- Your Pull Request has a proper title and description. ✔️  
- No Linter errors :heavy_check_mark: 
- Your Design looks awesome, keep rocking :rocket: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

- [OPTIONAL] It will be nice to add explicit steps to clone and run your project locally, as this will be of help to non-technical users. Please add descriptive steps from cloning your app to seeing the results displayed on the browser.. This includes `git clone URL` , `cd project_name`,  `npm install`, `npm start`, etc 🙃 

- please refer to this [template](https://github.com/microverseinc/readme-template), you can copy and paste the content but remember to customize it to your project.
Cheers :clinking_glasses:  and Happy coding!!! :dancers:💻  

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please ping me @BenMukebo when you comment so I can receive the notification.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-17 09:09 UTC, BenMukebo commented on README.md
> +### Usage
- [OPTIONAL] As requested by the previous reviewer, Let's add explicit steps for cloning your app, as this will be of help to non-technical users. You can put the steps to clone and run the project in a new Getting Started section. This includes `git clone URL` , `cd..`, etc.

2022-08-17 09:09 UTC, BenMukebo commented on README.md
> +This project is [MIT](./LICENSE) licensed.
- [ ] When I click the link to the `MIT.md` file that you added, I get this 404 `error`:

![16](https://user-images.githubusercontent.com/79058364/185080685-f8204b24-17cc-46e0-a0d5-3469f7e1ceee.png)


#### The reason for this is that there is no `MIT.md` file in the root directory of this project. Kindly attach the file. 👍

2022-08-17 09:38 UTC, merged

2022-08-17 09:48 UTC, AshwinCarvalho999 commented
Awesome, thanks!

On Wed, Aug 17, 2022, 2:39 PM Kasongo Mukebo Ben ***@***.***>
wrote:

> ***@***.**** approved this pull request.
> Status: Approve 🍾 👍 🎊 *Hi @AshwinCarvalho999
> <https://github.com/AshwinCarvalho999>*, *Congratulations! 🎉 Project
> Approved ✅*
>
> Your project is complete! There is nothing else to say other than... it's
> time to merge it [image: :shipit:]
> To Highlight 🥇
>
>    - Your Pull Request has a proper title and description. ✔️
>    - No Linter errors ✔️
>    - Your Design looks awesome, keep rocking 🚀
>
> Optional suggestions
>
> *Every comment with the [OPTIONAL] prefix won't stop the approval of this
> PR. However, I strongly recommend you to take them into account as they can
> make your code better. Some of them were simply missed by the previous
> reviewer and addressing them will really improve your application.*
>
>    -
>
>    [OPTIONAL] It will be nice to add explicit steps to clone and run your
>    project locally, as this will be of help to non-technical users. Please add
>    descriptive steps from cloning your app to seeing the results displayed on
>    the browser.. This includes git clone URL , cd project_name, npm
>    install, npm start, etc 🙃
>    -
>
>    please refer to this template
>    <https://github.com/microverseinc/readme-template>, you can copy and
>    paste the content but remember to customize it to your project.
>    Cheers 🥂 and Happy coding!!! 👯💻
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> Please ping me @BenMukebo <https://github.com/BenMukebo> when you comment
> so I can receive the notification.
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
> ------------------------------
>
> In README.md
> <https://github.com/AshwinCarvalho999/Portfolio-Mobile/pull/1#discussion_r947629484>
> :
>
> > +## Getting Started
>
> +
>
> +**This is an example of how you may give instructions on setting up your project locally.**
>
> +**Modify this file to match your project, remove sections that don't apply. For example: delete the testing section if the currect project doesn't require testing.**
>
> +
>
> +
>
> +To get a local copy up and running follow these simple example steps.
>
> +
>
> +### Prerequisites
>
> +
>
> +### Setup
>
> +
>
> +### Install
>
> +
>
> +### Usage
>
>
>
>    - [OPTIONAL] As requested by the previous reviewer, KIndly make sure
>    to add explicit steps for cloning your app, as this will be of help to
>    non-technical users. You can put the steps to clone and run the project in
>    a new Getting Started section under the project's description. This
>    includes git clone URL, cd.., etc.
>
> ------------------------------
>
> In README.md
> <https://github.com/AshwinCarvalho999/Portfolio-Mobile/pull/1#discussion_r947650030>
> :
>
> > +## Getting Started
>
> +
>
> +**This is an example of how you may give instructions on setting up your project locally.**
>
> +**Modify this file to match your project, remove sections that don't apply. For example: delete the testing section if the currect project doesn't require testing.**
>
> +
>
> +
>
> +To get a local copy up and running follow these simple example steps.
>
> +
>
> +### Prerequisites
>
> +
>
> +### Setup
>
> +
>
> +### Install
>
> +
>
> +### Usage
>
>
>
>    - [OPTIONAL] As requested by the previous reviewer, Let's add explicit
>    steps for cloning your app, as this will be of help to non-technical users.
>    You can put the steps to clone and run the project in a new Getting Started
>    section. This includes git clone URL , cd.., etc.
>
> ------------------------------
>
> In README.md
> <https://github.com/AshwinCarvalho999/Portfolio-Mobile/pull/1#discussion_r947651820>
> :
>
> > +## 📝 License
>
> +
>
> +This project is [MIT](./LICENSE) licensed.
>
>
>
>    - When I click the link to the MIT.md file that you added, I get this
>    404 error:
>
> [image: 16]
> <https://user-images.githubusercontent.com/79058364/185080685-f8204b24-17cc-46e0-a0d5-3469f7e1ceee.png>
> The reason for this is that there is no MIT.md file in the root directory
> of this project. Kindly attach the file. 👍
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/AshwinCarvalho999/Portfolio-Mobile/pull/1#pullrequestreview-1075292321>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AVKQBYR4M7N6M2QPTV2L7DLVZST5PANCNFSM54NQWACQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>